//请求 http://localhost:5111/video/:/transcode/universal/start.mpd?hasMDE=1&path=%2Flibrary%2Fmetadata%2F585&mediaIndex=0&partIndex=0
GET http://localhost:5111/video/:/transcode/universal/start.mpd?path=%2Flibrary%2Fmetadata%2F201&mediaIndex=0&partIndex=0
Accept: application/json
