version: '3.5'

services:

    service.nginx:
      image: nginx:alpine
      container_name: plex-nginx
      ports:
        - 8095:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
      restart: always
