FROM --platform=linux/arm64 ubuntu:18.04 AS stage1
# Install necessary packages
RUN apt-get update -y && apt-get install -y curl ca-certificates build-essential

RUN apt-get update -y
RUN apt-get install -y libx11-dev

# Download and install Go
ENV GO_VERSION 1.20.6
RUN curl -LO "https://go.dev/dl/go1.20.6.linux-arm64.tar.gz" && \
    tar -C /usr/local -xzf "go1.20.6.linux-arm64.tar.gz" && \
    rm "go1.20.6.linux-arm64.tar.gz"

# Set Go environment variables
ENV PATH="/usr/local/go/bin:${PATH}"
ENV GOPATH="/go"
ENV GOBIN="/go/bin"

# Create a directory for Go workspace
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

# Set CGO_ENABLED to enable cgo
RUN go env -w CGO_ENABLED=1

# Set the working directory
WORKDIR $GOPATH/src

COPY . .

RUN ls

# Print Go version to verify the installation
RUN go version

RUN go build -ldflags="-s -w " -trimpath  -o plex2alist-linux-arm64 main.go
# Your additional configurations and code can be added here.

FROM scratch AS export-stage
COPY --from=stage1 /go/src/plex2alist-linux-arm64 .

# By default, run bash for interactive access (optional)
CMD ["/bin/bash"]
